const easyProblems = [
    " Calcular el área de un rectángulo (base, altura → área)",
    "Convertir grados Celsius a Fahrenheit – igual, pero con fórmula.",
    "Determinar si un número es par o impar – olvídate del %; piensa: restar 2 hasta llegar a 0 o 1.",
    "Sumar dos números ingresados por el usuario.",
    "Calcular el promedio de tres notas.",
    "Encontrar el mayor de dos números.",
    "Encontrar el mayor de tres números – descompón en dos comparaciones.",
    "Calcular el perímetro de un círculo (radio → perímetro).",
    "Determinar si un año es bisiesto – reglas: divisible por 4, pero no por 100 a menos que también por 400.",
    "Leer un carácter y decir si es vocal – descompón: lista de vocales, comparar con cada una.",
    "Calcular el factorial de un número (iterativo) – subproblemas: contador, acumulador, bucle condicional.",
    "Mostrar los números del 1 al N – descompón: inicializar contador, condición de parada, incremento.",
    "Sumar los primeros N números naturales.",
    "Contar cuántos dígitos tiene un número entero – divide entre 10 hasta cero.",
    "Invertir un número de 3 cifras (ej: 123 → 321) – extraer unidades, decenas, centenas",
    "Calcular el IMC (peso, altura → índice, luego clasificación bajo/normal/sobre).",
    "Determinar si un triángulo es válido (tres lados, suma de dos > tercero).",
    "Clasificar un ángulo (agudo, recto, obtuso, llano).",
    "Convertir segundos a horas: minutos: segundos – divisiones y residuos.",
    "Tabla de multiplicar de un número(del 1 al 10).",
    "Contar números pares en un rango(desde A hasta B).",
    "Calcular el precio con descuento(porcentaje de descuento).",
    "Mostrar los divisores de un número – bucle que prueba resto cero.",
    "Determinar si un número es primo(versión simple: divisible solo por 1 y sí mismo).",
    "Calcular la suma de dígitos de un número.",
    "Intercambiar dos variables sin usar una tercera – truco de suma y resta.",
    "Leer 10 números y mostrar el mayor.",
    "Calcular la media de una lista de números(tamaño fijo).",
    "Generar los primeros N números de Fibonacci(F0 = 0, F1 = 1).",
    "Simular una calculadora básica(suma, resta, multiplica, divide – con validación de división por cero)."
]

export default easyProblems
